services:

  bitcoin-client:
    image: bitcoin
    container_name: bitcoin
    hostname: bitcoin
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./data/:/opt/graphsense/data:Z
      - ./docker/client.conf:/opt/graphsense/client.conf:Z
    networks:
      - graphsense-net
    ports:
      - 8332:8332
    restart: always

networks:
  graphsense-net:
    name: graphsense-net
